# === Environment ===
[variables]
JAVA_VERSION = "17"

# === Setup Phase ===
[phases.setup]
cmds = [
  "echo 'Setup phase'"
]

# === Build Phase ===
[phases.build]
cmds = [
  "chmod +x backend/mvnw || true",
  "cd backend && ./mvnw clean package -DskipTests"
]

# === Start Phase ===
[start]
cmd = "java -jar backend/target/urngh-0.0.1-SNAPSHOT.jar"

# === Required Files ===
[files]
required = [
  "backend/pom.xml",
  "backend/mvnw",
  "backend/src/main/resources/application.properties",
  "frontend/index.html",
  "frontend/*.css",
  "frontend/*.js"
]

# === HTTP Port ===
[ports]
http = 8080

# === Serve Frontend Static Files ===
[[static]]
source = "frontend"
serve = "/"
