# ===== Setup Phase =====
[phases.setup]
cmds = [
  "echo 'Setup phase'"
]

# ===== Build Phase =====
[phases.build]
cmds = [
  "cd backend && ./mvnw clean package -DskipTests"
]

# ===== Start Command =====
[start]
cmd = "java -jar backend/target/urngh-0.0.1-SNAPSHOT.jar"

# ===== Environment =====
[variables]
JAVA_VERSION = "17"

# ===== Required Files =====
[files]
required = [
  "backend/pom.xml",
  "backend/mvnw",
  "backend/src/main/resources/application.properties",
  "frontend/public/index.html"
]

# ===== HTTP Port =====
[ports]
http = 8080

# ===== Serve Frontend Static Files =====
[[static]]
source = "frontend/public"
serve = "/"
