[phases.setup]
command = "echo 'Setup phase'"

[phases.build]
cmds = [
  "cd backend && ./mvnw clean package -DskipTests"
]

[start]
command = "java -jar backend/target/urngh-0.0.1-SNAPSHOT.jar"

[variables]
JAVA_VERSION = "17"

[files]
required = [
  "backend/pom.xml",
  "backend/mvnw",
  "backend/src/main/resources/application.properties",
  "frontend/public/index.html"
]

[ports]
http = 8080

[[static]]
source = "frontend/public"
serve = "/"
